/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularyListsRouteImport } from './routes/vocabulary-lists'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as QuizHubRouteImport } from './routes/quiz-hub'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HangmanRouteImport } from './routes/hangman'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as GamesRouteImport } from './routes/games'
import { Route as DictionaryRouteImport } from './routes/dictionary'
import { Route as CultureRouteImport } from './routes/culture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsPrivacyRouteImport } from './routes/settings/privacy'
import { Route as QuizModeRouteImport } from './routes/quiz.$mode'
import { Route as QuizPlayTypeRouteImport } from './routes/quiz-play.$type'
import { Route as ConversationTopicRouteImport } from './routes/conversation.$topic'

const VocabularyListsRoute = VocabularyListsRouteImport.update({
  id: '/vocabulary-lists',
  path: '/vocabulary-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizHubRoute = QuizHubRouteImport.update({
  id: '/quiz-hub',
  path: '/quiz-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HangmanRoute = HangmanRouteImport.update({
  id: '/hangman',
  path: '/hangman',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionaryRoute = DictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureRoute = CultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/settings/privacy',
  path: '/settings/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizModeRoute = QuizModeRouteImport.update({
  id: '/quiz/$mode',
  path: '/quiz/$mode',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizPlayTypeRoute = QuizPlayTypeRouteImport.update({
  id: '/quiz-play/$type',
  path: '/quiz-play/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationTopicRoute = ConversationTopicRouteImport.update({
  id: '/conversation/$topic',
  path: '/conversation/$topic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/culture': typeof CultureRoute
  '/dictionary': typeof DictionaryRoute
  '/games': typeof GamesRoute
  '/guest': typeof GuestRoute
  '/guide': typeof GuideRoute
  '/hangman': typeof HangmanRoute
  '/home': typeof HomeRoute
  '/lessons': typeof LessonsRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quiz-hub': typeof QuizHubRoute
  '/setup': typeof SetupRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/skills': typeof SkillsRoute
  '/vocabulary-lists': typeof VocabularyListsRoute
  '/conversation/$topic': typeof ConversationTopicRoute
  '/quiz-play/$type': typeof QuizPlayTypeRoute
  '/quiz/$mode': typeof QuizModeRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/culture': typeof CultureRoute
  '/dictionary': typeof DictionaryRoute
  '/games': typeof GamesRoute
  '/guest': typeof GuestRoute
  '/guide': typeof GuideRoute
  '/hangman': typeof HangmanRoute
  '/home': typeof HomeRoute
  '/lessons': typeof LessonsRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quiz-hub': typeof QuizHubRoute
  '/setup': typeof SetupRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/skills': typeof SkillsRoute
  '/vocabulary-lists': typeof VocabularyListsRoute
  '/conversation/$topic': typeof ConversationTopicRoute
  '/quiz-play/$type': typeof QuizPlayTypeRoute
  '/quiz/$mode': typeof QuizModeRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/culture': typeof CultureRoute
  '/dictionary': typeof DictionaryRoute
  '/games': typeof GamesRoute
  '/guest': typeof GuestRoute
  '/guide': typeof GuideRoute
  '/hangman': typeof HangmanRoute
  '/home': typeof HomeRoute
  '/lessons': typeof LessonsRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quiz-hub': typeof QuizHubRoute
  '/setup': typeof SetupRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/skills': typeof SkillsRoute
  '/vocabulary-lists': typeof VocabularyListsRoute
  '/conversation/$topic': typeof ConversationTopicRoute
  '/quiz-play/$type': typeof QuizPlayTypeRoute
  '/quiz/$mode': typeof QuizModeRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/culture'
    | '/dictionary'
    | '/games'
    | '/guest'
    | '/guide'
    | '/hangman'
    | '/home'
    | '/lessons'
    | '/login'
    | '/memory'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/quiz-hub'
    | '/setup'
    | '/shop'
    | '/signup'
    | '/skills'
    | '/vocabulary-lists'
    | '/conversation/$topic'
    | '/quiz-play/$type'
    | '/quiz/$mode'
    | '/settings/privacy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/culture'
    | '/dictionary'
    | '/games'
    | '/guest'
    | '/guide'
    | '/hangman'
    | '/home'
    | '/lessons'
    | '/login'
    | '/memory'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/quiz-hub'
    | '/setup'
    | '/shop'
    | '/signup'
    | '/skills'
    | '/vocabulary-lists'
    | '/conversation/$topic'
    | '/quiz-play/$type'
    | '/quiz/$mode'
    | '/settings/privacy'
  id:
    | '__root__'
    | '/'
    | '/culture'
    | '/dictionary'
    | '/games'
    | '/guest'
    | '/guide'
    | '/hangman'
    | '/home'
    | '/lessons'
    | '/login'
    | '/memory'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/quiz-hub'
    | '/setup'
    | '/shop'
    | '/signup'
    | '/skills'
    | '/vocabulary-lists'
    | '/conversation/$topic'
    | '/quiz-play/$type'
    | '/quiz/$mode'
    | '/settings/privacy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CultureRoute: typeof CultureRoute
  DictionaryRoute: typeof DictionaryRoute
  GamesRoute: typeof GamesRoute
  GuestRoute: typeof GuestRoute
  GuideRoute: typeof GuideRoute
  HangmanRoute: typeof HangmanRoute
  HomeRoute: typeof HomeRoute
  LessonsRoute: typeof LessonsRoute
  LoginRoute: typeof LoginRoute
  MemoryRoute: typeof MemoryRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  QuizHubRoute: typeof QuizHubRoute
  SetupRoute: typeof SetupRoute
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  SkillsRoute: typeof SkillsRoute
  VocabularyListsRoute: typeof VocabularyListsRoute
  ConversationTopicRoute: typeof ConversationTopicRoute
  QuizPlayTypeRoute: typeof QuizPlayTypeRoute
  QuizModeRoute: typeof QuizModeRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulary-lists': {
      id: '/vocabulary-lists'
      path: '/vocabulary-lists'
      fullPath: '/vocabulary-lists'
      preLoaderRoute: typeof VocabularyListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-hub': {
      id: '/quiz-hub'
      path: '/quiz-hub'
      fullPath: '/quiz-hub'
      preLoaderRoute: typeof QuizHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hangman': {
      id: '/hangman'
      path: '/hangman'
      fullPath: '/hangman'
      preLoaderRoute: typeof HangmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary': {
      id: '/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof DictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture': {
      id: '/culture'
      path: '/culture'
      fullPath: '/culture'
      preLoaderRoute: typeof CultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$mode': {
      id: '/quiz/$mode'
      path: '/quiz/$mode'
      fullPath: '/quiz/$mode'
      preLoaderRoute: typeof QuizModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-play/$type': {
      id: '/quiz-play/$type'
      path: '/quiz-play/$type'
      fullPath: '/quiz-play/$type'
      preLoaderRoute: typeof QuizPlayTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation/$topic': {
      id: '/conversation/$topic'
      path: '/conversation/$topic'
      fullPath: '/conversation/$topic'
      preLoaderRoute: typeof ConversationTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CultureRoute: CultureRoute,
  DictionaryRoute: DictionaryRoute,
  GamesRoute: GamesRoute,
  GuestRoute: GuestRoute,
  GuideRoute: GuideRoute,
  HangmanRoute: HangmanRoute,
  HomeRoute: HomeRoute,
  LessonsRoute: LessonsRoute,
  LoginRoute: LoginRoute,
  MemoryRoute: MemoryRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  QuizHubRoute: QuizHubRoute,
  SetupRoute: SetupRoute,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  SkillsRoute: SkillsRoute,
  VocabularyListsRoute: VocabularyListsRoute,
  ConversationTopicRoute: ConversationTopicRoute,
  QuizPlayTypeRoute: QuizPlayTypeRoute,
  QuizModeRoute: QuizModeRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
