/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularyListsRouteImport } from './routes/vocabulary-lists'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as QuizHubRouteImport } from './routes/quiz-hub'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HangmanRouteImport } from './routes/hangman'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as GamesRouteImport } from './routes/games'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DictionaryRouteImport } from './routes/dictionary'
import { Route as CultureRouteImport } from './routes/culture'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CancelRouteImport } from './routes/cancel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CultureIndexRouteImport } from './routes/culture.index'
import { Route as QuizModeRouteImport } from './routes/quiz.$mode'
import { Route as QuizPlayTypeRouteImport } from './routes/quiz-play.$type'
import { Route as LessonIdRouteImport } from './routes/lesson.$id'
import { Route as CultureCityIdRouteImport } from './routes/culture.$cityId'
import { Route as ConversationTopicRouteImport } from './routes/conversation.$topic'

const VocabularyListsRoute = VocabularyListsRouteImport.update({
  id: '/vocabulary-lists',
  path: '/vocabulary-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizHubRoute = QuizHubRouteImport.update({
  id: '/quiz-hub',
  path: '/quiz-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HangmanRoute = HangmanRouteImport.update({
  id: '/hangman',
  path: '/hangman',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionaryRoute = DictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureRoute = CultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelRoute = CancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureIndexRoute = CultureIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CultureRoute,
} as any)
const QuizModeRoute = QuizModeRouteImport.update({
  id: '/quiz/$mode',
  path: '/quiz/$mode',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizPlayTypeRoute = QuizPlayTypeRouteImport.update({
  id: '/quiz-play/$type',
  path: '/quiz-play/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonIdRoute = LessonIdRouteImport.update({
  id: '/lesson/$id',
  path: '/lesson/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureCityIdRoute = CultureCityIdRouteImport.update({
  id: '/$cityId',
  path: '/$cityId',
  getParentRoute: () => CultureRoute,
} as any)
const ConversationTopicRoute = ConversationTopicRouteImport.update({
  id: '/conversation/$topic',
  path: '/conversation/$topic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cancel': typeof CancelRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/culture': typeof CultureRouteWithChildren
  '/dictionary': typeof DictionaryRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/games': typeof GamesRoute
  '/guide': typeof GuideRoute
  '/hangman': typeof HangmanRoute
  '/home': typeof HomeRoute
  '/lessons': typeof LessonsRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quiz-hub': typeof QuizHubRoute
  '/refund': typeof RefundRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/skills': typeof SkillsRoute
  '/success': typeof SuccessRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/vocabulary-lists': typeof VocabularyListsRoute
  '/conversation/$topic': typeof ConversationTopicRoute
  '/culture/$cityId': typeof CultureCityIdRoute
  '/lesson/$id': typeof LessonIdRoute
  '/quiz-play/$type': typeof QuizPlayTypeRoute
  '/quiz/$mode': typeof QuizModeRoute
  '/culture/': typeof CultureIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cancel': typeof CancelRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/dictionary': typeof DictionaryRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/games': typeof GamesRoute
  '/guide': typeof GuideRoute
  '/hangman': typeof HangmanRoute
  '/home': typeof HomeRoute
  '/lessons': typeof LessonsRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quiz-hub': typeof QuizHubRoute
  '/refund': typeof RefundRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/skills': typeof SkillsRoute
  '/success': typeof SuccessRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/vocabulary-lists': typeof VocabularyListsRoute
  '/conversation/$topic': typeof ConversationTopicRoute
  '/culture/$cityId': typeof CultureCityIdRoute
  '/lesson/$id': typeof LessonIdRoute
  '/quiz-play/$type': typeof QuizPlayTypeRoute
  '/quiz/$mode': typeof QuizModeRoute
  '/culture': typeof CultureIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cancel': typeof CancelRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/culture': typeof CultureRouteWithChildren
  '/dictionary': typeof DictionaryRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/games': typeof GamesRoute
  '/guide': typeof GuideRoute
  '/hangman': typeof HangmanRoute
  '/home': typeof HomeRoute
  '/lessons': typeof LessonsRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quiz-hub': typeof QuizHubRoute
  '/refund': typeof RefundRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/skills': typeof SkillsRoute
  '/success': typeof SuccessRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/vocabulary-lists': typeof VocabularyListsRoute
  '/conversation/$topic': typeof ConversationTopicRoute
  '/culture/$cityId': typeof CultureCityIdRoute
  '/lesson/$id': typeof LessonIdRoute
  '/quiz-play/$type': typeof QuizPlayTypeRoute
  '/quiz/$mode': typeof QuizModeRoute
  '/culture/': typeof CultureIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cancel'
    | '/checkout'
    | '/community'
    | '/culture'
    | '/dictionary'
    | '/forgot-password'
    | '/games'
    | '/guide'
    | '/hangman'
    | '/home'
    | '/lessons'
    | '/login'
    | '/memory'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/progress'
    | '/quiz-hub'
    | '/refund'
    | '/settings'
    | '/setup'
    | '/shop'
    | '/signup'
    | '/skills'
    | '/success'
    | '/support'
    | '/terms'
    | '/vocabulary-lists'
    | '/conversation/$topic'
    | '/culture/$cityId'
    | '/lesson/$id'
    | '/quiz-play/$type'
    | '/quiz/$mode'
    | '/culture/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cancel'
    | '/checkout'
    | '/community'
    | '/dictionary'
    | '/forgot-password'
    | '/games'
    | '/guide'
    | '/hangman'
    | '/home'
    | '/lessons'
    | '/login'
    | '/memory'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/progress'
    | '/quiz-hub'
    | '/refund'
    | '/settings'
    | '/setup'
    | '/shop'
    | '/signup'
    | '/skills'
    | '/success'
    | '/support'
    | '/terms'
    | '/vocabulary-lists'
    | '/conversation/$topic'
    | '/culture/$cityId'
    | '/lesson/$id'
    | '/quiz-play/$type'
    | '/quiz/$mode'
    | '/culture'
  id:
    | '__root__'
    | '/'
    | '/cancel'
    | '/checkout'
    | '/community'
    | '/culture'
    | '/dictionary'
    | '/forgot-password'
    | '/games'
    | '/guide'
    | '/hangman'
    | '/home'
    | '/lessons'
    | '/login'
    | '/memory'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/progress'
    | '/quiz-hub'
    | '/refund'
    | '/settings'
    | '/setup'
    | '/shop'
    | '/signup'
    | '/skills'
    | '/success'
    | '/support'
    | '/terms'
    | '/vocabulary-lists'
    | '/conversation/$topic'
    | '/culture/$cityId'
    | '/lesson/$id'
    | '/quiz-play/$type'
    | '/quiz/$mode'
    | '/culture/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CancelRoute: typeof CancelRoute
  CheckoutRoute: typeof CheckoutRoute
  CommunityRoute: typeof CommunityRoute
  CultureRoute: typeof CultureRouteWithChildren
  DictionaryRoute: typeof DictionaryRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GamesRoute: typeof GamesRoute
  GuideRoute: typeof GuideRoute
  HangmanRoute: typeof HangmanRoute
  HomeRoute: typeof HomeRoute
  LessonsRoute: typeof LessonsRoute
  LoginRoute: typeof LoginRoute
  MemoryRoute: typeof MemoryRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  QuizHubRoute: typeof QuizHubRoute
  RefundRoute: typeof RefundRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  SkillsRoute: typeof SkillsRoute
  SuccessRoute: typeof SuccessRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  VocabularyListsRoute: typeof VocabularyListsRoute
  ConversationTopicRoute: typeof ConversationTopicRoute
  LessonIdRoute: typeof LessonIdRoute
  QuizPlayTypeRoute: typeof QuizPlayTypeRoute
  QuizModeRoute: typeof QuizModeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulary-lists': {
      id: '/vocabulary-lists'
      path: '/vocabulary-lists'
      fullPath: '/vocabulary-lists'
      preLoaderRoute: typeof VocabularyListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-hub': {
      id: '/quiz-hub'
      path: '/quiz-hub'
      fullPath: '/quiz-hub'
      preLoaderRoute: typeof QuizHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hangman': {
      id: '/hangman'
      path: '/hangman'
      fullPath: '/hangman'
      preLoaderRoute: typeof HangmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary': {
      id: '/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof DictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture': {
      id: '/culture'
      path: '/culture'
      fullPath: '/culture'
      preLoaderRoute: typeof CultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancel': {
      id: '/cancel'
      path: '/cancel'
      fullPath: '/cancel'
      preLoaderRoute: typeof CancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture/': {
      id: '/culture/'
      path: '/'
      fullPath: '/culture/'
      preLoaderRoute: typeof CultureIndexRouteImport
      parentRoute: typeof CultureRoute
    }
    '/quiz/$mode': {
      id: '/quiz/$mode'
      path: '/quiz/$mode'
      fullPath: '/quiz/$mode'
      preLoaderRoute: typeof QuizModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-play/$type': {
      id: '/quiz-play/$type'
      path: '/quiz-play/$type'
      fullPath: '/quiz-play/$type'
      preLoaderRoute: typeof QuizPlayTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$id': {
      id: '/lesson/$id'
      path: '/lesson/$id'
      fullPath: '/lesson/$id'
      preLoaderRoute: typeof LessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture/$cityId': {
      id: '/culture/$cityId'
      path: '/$cityId'
      fullPath: '/culture/$cityId'
      preLoaderRoute: typeof CultureCityIdRouteImport
      parentRoute: typeof CultureRoute
    }
    '/conversation/$topic': {
      id: '/conversation/$topic'
      path: '/conversation/$topic'
      fullPath: '/conversation/$topic'
      preLoaderRoute: typeof ConversationTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CultureRouteChildren {
  CultureCityIdRoute: typeof CultureCityIdRoute
  CultureIndexRoute: typeof CultureIndexRoute
}

const CultureRouteChildren: CultureRouteChildren = {
  CultureCityIdRoute: CultureCityIdRoute,
  CultureIndexRoute: CultureIndexRoute,
}

const CultureRouteWithChildren =
  CultureRoute._addFileChildren(CultureRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CancelRoute: CancelRoute,
  CheckoutRoute: CheckoutRoute,
  CommunityRoute: CommunityRoute,
  CultureRoute: CultureRouteWithChildren,
  DictionaryRoute: DictionaryRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GamesRoute: GamesRoute,
  GuideRoute: GuideRoute,
  HangmanRoute: HangmanRoute,
  HomeRoute: HomeRoute,
  LessonsRoute: LessonsRoute,
  LoginRoute: LoginRoute,
  MemoryRoute: MemoryRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  QuizHubRoute: QuizHubRoute,
  RefundRoute: RefundRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  SkillsRoute: SkillsRoute,
  SuccessRoute: SuccessRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  VocabularyListsRoute: VocabularyListsRoute,
  ConversationTopicRoute: ConversationTopicRoute,
  LessonIdRoute: LessonIdRoute,
  QuizPlayTypeRoute: QuizPlayTypeRoute,
  QuizModeRoute: QuizModeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
